DROP ALL OBJECTS DELETE FILES;

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    ID    IDENTITY          NOT NULL PRIMARY KEY,
    NAME  CHARACTER VARYING NOT NULL,
    EMAIL CHARACTER VARYING NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.REQUESTS
(
    ID           IDENTITY NOT NULL PRIMARY KEY,
    DESCRIPTION  CHARACTER VARYING,
    REQUESTER_ID INTEGER REFERENCES PUBLIC.USERS (ID),
    CREATED      TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS PUBLIC.ITEMS
(
    ID           IDENTITY          NOT NULL PRIMARY KEY,
    NAME         CHARACTER VARYING NOT NULL,
    DESCRIPTION  CHARACTER VARYING,
    IS_AVAILABLE BOOLEAN,
    OWNER_ID     INTEGER REFERENCES PUBLIC.USERS (ID),
    REQUEST_ID   INTEGER REFERENCES PUBLIC.REQUESTS (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.STATUSES
(
    ID   IDENTITY NOT NULL PRIMARY KEY,
    NAME CHARACTER VARYING
);

CREATE TABLE IF NOT EXISTS PUBLIC.BOOKINGS
(
    ID         IDENTITY NOT NULL PRIMARY KEY,
    START_DATE TIMESTAMP WITHOUT TIME ZONE,
    END_DATE   TIMESTAMP WITHOUT TIME ZONE,
    ITEM_ID    INTEGER REFERENCES PUBLIC.ITEMS (ID),
    BOOKER_ID  INTEGER REFERENCES PUBLIC.USERS (ID),
    STATUS_ID  INTEGER REFERENCES PUBLIC.STATUSES (ID) --TODO: OR NAME

);

CREATE TABLE IF NOT EXISTS PUBLIC.COMMENTS
(
    ID        IDENTITY NOT NULL PRIMARY KEY,
    TEXT      CHARACTER VARYING,
    ITEM_ID   INTEGER REFERENCES PUBLIC.ITEMS (ID),
    AUTHOR_ID INTEGER REFERENCES PUBLIC.USERS (ID)
);
