DELETE
FROM PUBLIC.COMMENTS;
DELETE
FROM PUBLIC.BOOKINGS;
DELETE
FROM PUBLIC.STATUSES;
DELETE
FROM PUBLIC.ITEMS;
DELETE
FROM PUBLIC.REQUESTS;
DELETE
FROM PUBLIC.USERS;

INSERT INTO PUBLIC.STATUSES
(ID, NAME)
VALUES (0, 'WAITING'),
       (1, 'APPROVED'),
       (2, 'REJECTED'),
       (3, 'CANCELED');